version: 4.0

id: semantic-release-config
uid: 152829183

about:
  title: Semantic Release Config
  alias: semantic-release-config
  description: TELUS flavor of semantic-release, to automate the package release workflow
  type: 'module'
  target: npm

contacts:
  - type: Project Owner
    name: Shimona Jain
    email: shimona.jain@telus.com

  - type: Team
    name: ptt-ti
    members_uri: https://github.com/orgs/telus/teams/ptt-ti/members
    repositories_uri: https://github.com/orgs/telus/teams/ptt-ti/repositories

environments:
  - type: production
    title: NPM Package
    uri: https://www.npmjs.com/package/@telus/semantic-release-config

references:
  - title: git
    description: Source Code
    uri: https://github.com/telus/semantic-release-config
