version: 2.1

executors:
  app:
    working_directory: /src

    docker:
      - image: node:alpine

commands:
  setup:
    steps:
      - run:
          name: Setup Container
          command: "apk add --update --no-cache ca-certificates git openssh g++ make python"

jobs:
  release:
    executor: app
    steps:
      - setup
      - checkout
      - run: npm ci
      - run: npx semantic-release

workflows:
  version: 2
  run:
    jobs:
      - release:
          context: npm-library
