name: 'Publish package on merge to master'

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install deps
        run: npm ci

      - name: Dryrun release
        run: npm run release:dryrun
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Semantic release
        run: npm run release
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
